// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// project
List project(const NumericMatrix& m_y, const NumericMatrix& m_theta, const NumericMatrix& m_beta);
RcppExport SEXP _ppslp_project(SEXP m_ySEXP, SEXP m_thetaSEXP, SEXP m_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type m_y(m_ySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type m_theta(m_thetaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type m_beta(m_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(project(m_y, m_theta, m_beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ppslp_project", (DL_FUNC) &_ppslp_project, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ppslp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
