# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Projection
#'
#' Compute scalar p_i for each y_i.
#' @param y data matrix y
#' @param theta weight matrix theta
#' @param m_Beta transform weight matrix m_Beta
#' @return A structure represent the projected points, including
#'         \code{m_B} the projected spline matrix
#'         \item{v_pi}{The projection index for each point}
#'         \item{dist}{The total squared distance from the curve}
#'         \item{dist_ind}{The squared distances from the curve to each of the respective points}
#'
#' @keywords Projection, Spline
#' @noRd
#' @examples
#' y <- matrix(c(13, -4, 2, -4, 11, -2, 2, -2, 8, 10), 5, 2, byrow = TRUE)
#' theta <- matrix(c(4.92, -2.67, 5.83, -1.76, 6.74, -0.85,
#'                   7.65, 0.054, 8.56, 0.96, 9.47, 1.87), 6, 2, byrow = TRUE)
#' m_Beta <- diff(theta)
#' out <- f_projection(y, theta, m_Beta)
#' proj_p <- out$m_B %*% theta
#' plot(y[, 1], y[, 2], type = "o")
project <- function(m_y, m_theta, m_beta) {
    .Call('_ppslp_project', PACKAGE = 'ppslp', m_y, m_theta, m_beta)
}

